name: RSAIGE
channels:
  - r
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _r-mutex=1.0.0=anacondar_1
  - attrs=19.3.0=py_0
  - backports=1.0=py_2
  - backports.shutil_get_terminal_size=1.0.0=py27_2
  - backports_abc=0.5=py27_0
  - binutils_impl_linux-64=2.28.1=had2808c_3
  - binutils_linux-64=7.2.0=had2808c_27
  - bleach=3.1.0=py27_0
  - boost=1.70.0=py27h9de70de_1
  - boost-cpp=1.70.0=ha2d47e9_1
  - bwidget=1.9.11=1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.9.11=hecc5488_0
  - cairo=1.14.12=h8948797_3
  - certifi=2019.9.11=py27_0
  - cmake=3.14.0=h52cb24c_0
  - configparser=4.0.2=py27_0
  - contextlib2=0.6.0=py_0
  - curl=7.65.3=hbc83047_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py27_0
  - enum34=1.1.6=py27_1
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - fribidi=1.0.5=h7b6447c_0
  - functools32=3.2.3.2=py27_1
  - futures=3.3.0=py27_0
  - gcc_impl_linux-64=7.2.0=habb00fd_3
  - gcc_linux-64=7.2.0=h550dcbe_27
  - gettext=0.19.8.1=hc5be6a0_1002
  - gfortran_impl_linux-64=7.2.0=hdf63c60_3
  - gfortran_linux-64=7.2.0=h550dcbe_27
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - graphite2=1.3.13=h23475e2_0
  - gsl=2.4=h14c3975_4
  - gxx_impl_linux-64=7.2.0=hdf63c60_3
  - gxx_linux-64=7.2.0=h550dcbe_27
  - harfbuzz=1.8.8=hffaf4a1_0
  - icu=58.2=h9c2bf20_1
  - importlib_metadata=0.23=py27_0
  - ipaddress=1.0.23=py_0
  - ipykernel=4.10.0=py27_0
  - ipython=5.8.0=py27_0
  - ipython_genutils=0.2.0=py27_0
  - jinja2=2.10.3=py_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.1.1=py27_0
  - jupyter_client=5.3.4=py27_0
  - jupyter_core=4.6.1=py27_0
  - krb5=1.16.1=h173b8e3_7
  - lapack=3.6.1=ha44fe06_2
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libcurl=7.65.3=h20c2e04_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran=3.0.0=1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h6e990d7_3
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libssh2=1.8.2=h1ba5d50_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - make=4.2.1=h1bed415_1
  - markupsafe=1.1.1=py27h7b6447c_0
  - mistune=0.8.4=py27h7b6447c_0
  - more-itertools=5.0.0=py27_0
  - nbconvert=5.6.1=py27_0
  - nbformat=4.4.0=py27_0
  - ncurses=6.1=he6710b0_1
  - notebook=5.7.8=py27_0
  - numpy=1.16.5=py27h95a1406_0
  - openblas=0.3.7=h6e990d7_3
  - openssl=1.1.1d=h516909a_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py27_1
  - pango=1.42.4=h049681c_0
  - pathlib2=2.3.5=py27_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py27_0
  - pickleshare=0.7.5=py27_0
  - pip=19.3.1=py27_0
  - pixman=0.38.0=h7b6447c_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=1.0.15=py27_0
  - ptyprocess=0.6.0=py27_0
  - pygments=2.4.2=py_0
  - pyrsistent=0.15.4=py27h7b6447c_0
  - python=2.7.17=h9bab390_0
  - python-dateutil=2.8.1=py_0
  - pyzmq=17.1.2=py27h14c3975_0
  - r-askpass=1.0=r36h14c3975_0
  - r-assertthat=0.2.1=r36h6115d3f_0
  - r-backports=1.1.4=r36h96ca727_0
  - r-base=3.6.1=h9bb98a2_1
  - r-base64enc=0.1_3=r36h96ca727_4
  - r-bh=1.69.0_1=r36h6115d3f_0
  - r-boot=1.3_20=r36h6115d3f_0
  - r-broom=0.5.2=r36h6115d3f_0
  - r-callr=3.2.0=r36h6115d3f_0
  - r-caret=6.0_83=r36h96ca727_0
  - r-cellranger=1.1.0=r36h6115d3f_0
  - r-class=7.3_15=r36h96ca727_0
  - r-cli=1.1.0=r36h6115d3f_0
  - r-clipr=0.6.0=r36h6115d3f_0
  - r-clisymbols=1.2.0=r36h6115d3f_1002
  - r-cluster=2.0.8=r36ha65eedd_0
  - r-codetools=0.2_16=r36h6115d3f_0
  - r-colorspace=1.4_1=r36h96ca727_0
  - r-crayon=1.3.4=r36h6115d3f_0
  - r-curl=3.3=r36h96ca727_0
  - r-data.table=1.12.2=r36h96ca727_0
  - r-dbi=1.0.0=r36h6115d3f_0
  - r-dbplyr=1.4.0=r36h6115d3f_0
  - r-desc=1.2.0=r36h6115d3f_1002
  - r-devtools=2.0.2=r36h6115d3f_0
  - r-dichromat=2.0_0=r36h6115d3f_4
  - r-digest=0.6.18=r36h96ca727_0
  - r-dplyr=0.8.0.1=r36h29659fb_0
  - r-ellipsis=0.1.0=r36h96ca727_0
  - r-essentials=3.6.0=r36_0
  - r-evaluate=0.13=r36h6115d3f_0
  - r-fansi=0.4.0=r36h96ca727_0
  - r-forcats=0.4.0=r36h6115d3f_0
  - r-foreach=1.4.4=r36h6115d3f_0
  - r-foreign=0.8_71=r36h96ca727_0
  - r-formatr=1.6=r36h6115d3f_0
  - r-fs=1.2.7=r36h29659fb_0
  - r-generics=0.0.2=r36h6115d3f_0
  - r-getopt=1.20.3=r36_1
  - r-ggplot2=3.1.1=r36h6115d3f_0
  - r-gh=1.0.1=r36h6115d3f_1002
  - r-git2r=0.26.1=r36h5ca76e2_1
  - r-glmnet=2.0_16=r36ha65eedd_0
  - r-glue=1.3.1=r36h96ca727_0
  - r-gower=0.2.0=r36h96ca727_0
  - r-gtable=0.3.0=r36h6115d3f_0
  - r-haven=2.1.0=r36h29659fb_0
  - r-hexbin=1.27.2=r36ha65eedd_0
  - r-highr=0.8=r36h6115d3f_0
  - r-hms=0.4.2=r36h6115d3f_0
  - r-htmltools=0.3.6=r36h29659fb_0
  - r-htmlwidgets=1.3=r36h6115d3f_0
  - r-httpuv=1.5.1=r36h29659fb_0
  - r-httr=1.4.0=r36h6115d3f_0
  - r-ini=0.3.1=r36h6115d3f_1002
  - r-ipred=0.9_8=r36h96ca727_0
  - r-irdisplay=0.7.0=r36h6115d3f_0
  - r-irkernel=0.8.15=r36_0
  - r-iterators=1.0.10=r36h6115d3f_0
  - r-jsonlite=1.6=r36h96ca727_0
  - r-kernsmooth=2.23_15=r36ha65eedd_4
  - r-knitr=1.22=r36h6115d3f_0
  - r-labeling=0.3=r36h6115d3f_4
  - r-later=0.8.0=r36h29659fb_0
  - r-lattice=0.20_38=r36h96ca727_0
  - r-lava=1.6.5=r36h6115d3f_0
  - r-lazyeval=0.2.2=r36h96ca727_0
  - r-lubridate=1.7.4=r36h29659fb_0
  - r-magrittr=1.5=r36h6115d3f_4
  - r-maps=3.3.0=r36h96ca727_0
  - r-markdown=0.9=r36h96ca727_0
  - r-mass=7.3_51.3=r36h96ca727_0
  - r-matrix=1.2_17=r36hcdcec82_1
  - r-memoise=1.1.0=r36h6115d3f_1003
  - r-mgcv=1.8_28=r36h96ca727_0
  - r-mime=0.6=r36h96ca727_0
  - r-modelmetrics=1.2.2=r36h29659fb_0
  - r-modelr=0.1.4=r36h6115d3f_0
  - r-munsell=0.5.0=r36h6115d3f_0
  - r-nlme=3.1_139=r36ha65eedd_0
  - r-nnet=7.3_12=r36h96ca727_0
  - r-numderiv=2016.8_1=r36h6115d3f_0
  - r-openssl=1.3=r36h96ca727_0
  - r-optparse=1.6.4=r36h6115d3f_0
  - r-pbdzmq=0.3_3=r36h29659fb_0
  - r-pillar=1.3.1=r36h6115d3f_0
  - r-pkgbuild=1.0.6=r36h6115d3f_0
  - r-pkgconfig=2.0.2=r36h6115d3f_0
  - r-pkgload=1.0.2=r36h0357c0b_1001
  - r-plogr=0.2.0=r36h6115d3f_0
  - r-plyr=1.8.4=r36h29659fb_0
  - r-prettyunits=1.0.2=r36h6115d3f_0
  - r-processx=3.3.0=r36h96ca727_0
  - r-prodlim=2018.04.18=r36h29659fb_0
  - r-progress=1.2.0=r36h6115d3f_0
  - r-promises=1.0.1=r36h29659fb_0
  - r-ps=1.3.0=r36h96ca727_0
  - r-purrr=0.3.2=r36h96ca727_0
  - r-quantmod=0.4_14=r36h6115d3f_0
  - r-r6=2.4.0=r36h6115d3f_0
  - r-randomforest=4.6_14=r36ha65eedd_0
  - r-rbokeh=0.6.3=r36_0
  - r-rcmdcheck=1.3.3=r36h6115d3f_2
  - r-rcolorbrewer=1.1_2=r36h6115d3f_0
  - r-rcpp=1.0.1=r36h29659fb_0
  - r-rcpparmadillo=0.9.300.2.0=r36h29659fb_0
  - r-rcppeigen=0.3.3.7.0=r36h0357c0b_0
  - r-rcppparallel=4.4.4=r36h0357c0b_0
  - r-rcpproll=0.3.0=r36h29659fb_0
  - r-readr=1.3.1=r36h29659fb_0
  - r-readxl=1.3.1=r36h29659fb_0
  - r-recipes=0.1.5=r36h6115d3f_0
  - r-recommended=3.6.0=r36_0
  - r-rematch=1.0.1=r36h6115d3f_0
  - r-remotes=2.1.0=r36h6115d3f_1
  - r-repr=0.19.2=r36h6115d3f_0
  - r-reprex=0.2.1=r36h6115d3f_0
  - r-reshape2=1.4.3=r36h29659fb_0
  - r-rlang=0.3.4=r36h96ca727_0
  - r-rmarkdown=1.12=r36h6115d3f_0
  - r-rpart=4.1_15=r36h96ca727_0
  - r-rprojroot=1.3_2=r36h6115d3f_1002
  - r-rstudioapi=0.10=r36h6115d3f_0
  - r-rvest=0.3.3=r36h6115d3f_0
  - r-scales=1.0.0=r36h29659fb_0
  - r-selectr=0.4_1=r36h6115d3f_0
  - r-sessioninfo=1.1.1=r36h6115d3f_1001
  - r-shiny=1.3.2=r36h6115d3f_0
  - r-skat=1.3.2.1=r36he1b5a44_1002
  - r-sourcetools=0.1.7=r36h29659fb_0
  - r-spatest=3.0.0=r36h6115d3f_1001
  - r-spatial=7.3_11=r36h96ca727_4
  - r-squarem=2017.10_1=r36h6115d3f_0
  - r-stringi=1.4.3=r36h29659fb_0
  - r-stringr=1.4.0=r36h6115d3f_0
  - r-survival=2.44_1.1=r36h96ca727_0
  - r-sys=3.2=r36h96ca727_0
  - r-tibble=2.1.1=r36h96ca727_0
  - r-tidyr=0.8.3=r36h29659fb_0
  - r-tidyselect=0.2.5=r36h29659fb_0
  - r-tidyverse=1.2.1=r36h6115d3f_0
  - r-timedate=3043.102=r36h6115d3f_0
  - r-tinytex=0.12=r36h6115d3f_0
  - r-ttr=0.23_4=r36ha65eedd_0
  - r-usethis=1.5.0=r36h6115d3f_0
  - r-utf8=1.1.4=r36h96ca727_0
  - r-uuid=0.1_2=r36h96ca727_4
  - r-viridislite=0.3.0=r36h6115d3f_0
  - r-whisker=0.3_2=r36h6115d3f_4
  - r-withr=2.1.2=r36h6115d3f_0
  - r-xfun=0.6=r36h6115d3f_0
  - r-xml2=1.2.0=r36h29659fb_0
  - r-xopen=1.0.0=r36h6115d3f_1002
  - r-xtable=1.8_4=r36h6115d3f_0
  - r-xts=0.11_2=r36h96ca727_0
  - r-yaml=2.2.0=r36h96ca727_0
  - r-zoo=1.8_6=r36h96ca727_0
  - readline=7.0=h7b6447c_5
  - rhash=1.3.8=h1ba5d50_0
  - scandir=1.10.0=py27h7b6447c_0
  - send2trash=1.5.0=py27_0
  - setuptools=41.6.0=py27_0
  - simplegeneric=0.8.1=py27_2
  - singledispatch=3.4.0.3=py27_0
  - six=1.13.0=py27_0
  - sqlite=3.30.1=h7b6447c_0
  - terminado=0.8.2=py27_0
  - testpath=0.4.2=py27_0
  - tk=8.6.8=hbc83047_0
  - tktable=2.10=h14c3975_0
  - tornado=5.1.1=py27h7b6447c_0
  - traitlets=4.3.3=py27_0
  - wcwidth=0.1.7=py27_0
  - webencodings=0.5.1=py27_1
  - wheel=0.33.6=py27_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.2.5=hf484d3e_1
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
prefix: /home/wei/anaconda2/envs/RSAIGE

